server:
  port: 3333
spring:
  application:
    name: GATEWAY-API

zuul:
  prefix: /ms
  routes:
    greet:
     path: /api1/**
     serviceId: WELCOME-API
    welcome:
     path: /api2/**
     serviceId: GREET-API





